name: Theme Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.liquid'
      - '**/*.js'
      - '**/*.css'
      - '**/*.scss'
      - 'templates/**/*'
      - 'sections/**/*'
      - 'snippets/**/*'
      - 'layout/**/*'
      - 'assets/**/*'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          theme_root: .
